version: "2"

networks:
  consoapp.net:
    driver: bridge

services:
  
  apiBackoffice:
    image: node
    container_name: apiBackoffice
    user: "node"
    working_dir: /api/apiBackoffice
    volumes:
      - ./api:/api/apiBackoffice
    command: "npm run dev"
    ports:
      - "8080:8080"
    networks: 
      - 'geoquizz'
    links: 
      - database:mongodb

  apiMobile:
    image: node
    container_name: apiMobile
    user: "node"
    working_dir: /api/apiMobile
    volumes:
      - ./api:/api/apiMobile
    command: "npm run dev"
    ports:
      - "8081:8081"
    networks: 
      - 'geoquizz'
    links: 
      - database:mongodb

  apiPlayer:
    image: node
    container_name: apiPlayer
    user: "node"
    working_dir: /api/apiPlayer
    volumes:
      - ./api:/api/apiPlayer
    command: "npm run dev"
    ports:
      - "8082:8082"
    networks: 
      - 'geoquizz'
    links: 
      - database:mongodb
      
  database:
    image: mongo
    restart: always
    container_name: database
    environment:
        - MONGO_INITDB_DATABASE=Geoquizz
        - MONGO_INITDB_USERNAME=root
        - MONGO_INITDB_PASSWORD=example
    volumes:
        - ./mongo-volume:/data/db
    ports:
        - '27017:27017'
    networks: 
        - 'geoquizz'

  dbmanager:
    image: mongo-express
    networks:
      - geoquizz
    ports:
      - "8090:8090"
    links:
      - database:mongo
