version: "2"

networks: 
  geoquizz:
    driver: bridge

services:
  
  apiBackoffice:
    image: node
    environment:
      - NODE_ENV=production
#      - http_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
#      - https_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
    container_name: apiBackoffice
    user: "node"
    working_dir: /api
    volumes:
      - ./apiBackoffice:/api
    command: "npm run dev"
    ports:
      - "8081:8080"
    networks: 
      - 'geoquizz'
    links: 
      - databaseGeoQuizz:mongodb

  apiMobile:
    environment:
      - NODE_ENV=production
#      - http_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
#      - https_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
    image: node
    container_name: apiMobile
    user: "node"
    working_dir: /api
    volumes:
      - ./apiMobile:/api
    command: "npm run dev"
    ports:
      - "8082:8080"
    networks: 
      - 'geoquizz'
    links: 
      - databaseGeoQuizz:mongodb

  apiPlayer:
    environment:
      - NODE_ENV=production
#      - http_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
#      - https_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
    image: node
    container_name: apiPlayer
    user: "node"
    working_dir: /api
    volumes:
      - ./apiPlayer:/api
    command: "npm run dev"
    ports:
      - "8083:8080"
    networks: 
      - 'geoquizz'
    links: 
      - databaseGeoQuizz:mongodb
      
  databaseGeoQuizz:
    image: mongo
    restart: always
    container_name: databaseGeoQuizz
    environment:
#        - http_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
#        - https_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
        - MONGO_INITDB_DATABASE=Geoquizz
        - MONGO_INITDB_USERNAME=root
        - MONGO_INITDB_PASSWORD=example
    volumes:
        - ./mongo-volume:/data/db
    ports:
        - '27017:27017'
    networks: 
        - 'geoquizz'

  dbmanager:
    image: mongo-express
    networks:
      - geoquizz
    ports:
      - "8090:8081"
    links:
      - databaseGeoQuizz:mongo
